name: push
on:
  workflow_dispatch:
    inputs:
      title:
        default: "EMERGENCY"
      body:
        default: "check j1primeai email"
jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      T: ${{ github.event.inputs.title }}
      B: ${{ github.event.inputs.body }}
    steps:
      - run: curl -s -H "Title: $T" -H "Priority: urgent" -H "Tags: rotating_light" -d "$B" https://ntfy.sh/sharpsheet-608c226b9e7a
